//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBook.Domain.AddressBookServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Requests")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.GetAllPeopleRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.AddPersonRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.DeletePeopleRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.GetPersonRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.UpdatePersonRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.GetAllStatesRequest))]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeaderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllPeopleRequest", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Requests")]
    [System.SerializableAttribute()]
    public partial class GetAllPeopleRequest : AddressBook.Domain.AddressBookServiceReference.Request {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddPersonRequest", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Requests")]
    [System.SerializableAttribute()]
    public partial class AddPersonRequest : AddressBook.Domain.AddressBookServiceReference.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AddressBook.Domain.AddressBookServiceReference.PersonRecord PersonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AddressBook.Domain.AddressBookServiceReference.PersonRecord Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeletePeopleRequest", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Requests")]
    [System.SerializableAttribute()]
    public partial class DeletePeopleRequest : AddressBook.Domain.AddressBookServiceReference.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> PersonIdentifiersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> PersonIdentifiers {
            get {
                return this.PersonIdentifiersField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonIdentifiersField, value) != true)) {
                    this.PersonIdentifiersField = value;
                    this.RaisePropertyChanged("PersonIdentifiers");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPersonRequest", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Requests")]
    [System.SerializableAttribute()]
    public partial class GetPersonRequest : AddressBook.Domain.AddressBookServiceReference.Request {
        
        private string PersonIdentifierField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PersonIdentifier {
            get {
                return this.PersonIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonIdentifierField, value) != true)) {
                    this.PersonIdentifierField = value;
                    this.RaisePropertyChanged("PersonIdentifier");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdatePersonRequest", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Requests")]
    [System.SerializableAttribute()]
    public partial class UpdatePersonRequest : AddressBook.Domain.AddressBookServiceReference.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AddressBook.Domain.AddressBookServiceReference.PersonRecord PersonRecordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AddressBook.Domain.AddressBookServiceReference.PersonRecord PersonRecord {
            get {
                return this.PersonRecordField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonRecordField, value) != true)) {
                    this.PersonRecordField = value;
                    this.RaisePropertyChanged("PersonRecord");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllStatesRequest", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Requests")]
    [System.SerializableAttribute()]
    public partial class GetAllStatesRequest : AddressBook.Domain.AddressBookServiceReference.Request {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonRecord", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Records")]
    [System.SerializableAttribute()]
    public partial class PersonRecord : AddressBook.Domain.AddressBookServiceReference.Record {
        
        private AddressBook.Domain.AddressBookServiceReference.AddressRecord AddressField;
        
        private AddressBook.Domain.AddressBookServiceReference.EmailRecord EmailField;
        
        private AddressBook.Domain.AddressBookServiceReference.NameRecord NameField;
        
        private string PersonIdentifierField;
        
        private AddressBook.Domain.AddressBookServiceReference.PhoneRecord PhoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AddressBook.Domain.AddressBookServiceReference.AddressRecord Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AddressBook.Domain.AddressBookServiceReference.EmailRecord Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AddressBook.Domain.AddressBookServiceReference.NameRecord Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PersonIdentifier {
            get {
                return this.PersonIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonIdentifierField, value) != true)) {
                    this.PersonIdentifierField = value;
                    this.RaisePropertyChanged("PersonIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AddressBook.Domain.AddressBookServiceReference.PhoneRecord Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Record", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Records")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.StateRecord))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.AddressRecord))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.EmailRecord))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.NameRecord))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.PhoneRecord))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.PersonRecord))]
    public partial class Record : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StateRecord", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Records")]
    [System.SerializableAttribute()]
    public partial class StateRecord : AddressBook.Domain.AddressBookServiceReference.Record {
        
        private string StateIdentifierField;
        
        private string StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string StateIdentifier {
            get {
                return this.StateIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.StateIdentifierField, value) != true)) {
                    this.StateIdentifierField = value;
                    this.RaisePropertyChanged("StateIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressRecord", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Records")]
    [System.SerializableAttribute()]
    public partial class AddressRecord : AddressBook.Domain.AddressBookServiceReference.Record {
        
        private string AddressIdentifierField;
        
        private string StreetField;
        
        private string CityField;
        
        private string StateField;
        
        private string ZipField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AddressIdentifier {
            get {
                return this.AddressIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressIdentifierField, value) != true)) {
                    this.AddressIdentifierField = value;
                    this.RaisePropertyChanged("AddressIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailRecord", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Records")]
    [System.SerializableAttribute()]
    public partial class EmailRecord : AddressBook.Domain.AddressBookServiceReference.Record {
        
        private string EmailIdentifierField;
        
        private string EmailField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EmailIdentifier {
            get {
                return this.EmailIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdentifierField, value) != true)) {
                    this.EmailIdentifierField = value;
                    this.RaisePropertyChanged("EmailIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameRecord", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Records")]
    [System.SerializableAttribute()]
    public partial class NameRecord : AddressBook.Domain.AddressBookServiceReference.Record {
        
        private string NameIdentifierField;
        
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        private string LastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NameIdentifier {
            get {
                return this.NameIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.NameIdentifierField, value) != true)) {
                    this.NameIdentifierField = value;
                    this.RaisePropertyChanged("NameIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneRecord", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Records")]
    [System.SerializableAttribute()]
    public partial class PhoneRecord : AddressBook.Domain.AddressBookServiceReference.Record {
        
        private string PhoneIdentifierField;
        
        private string PhoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PhoneIdentifier {
            get {
                return this.PhoneIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneIdentifierField, value) != true)) {
                    this.PhoneIdentifierField = value;
                    this.RaisePropertyChanged("PhoneIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Responses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.GetAllPeopleResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.AddPersonResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.DeletePeopleResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.GetPersonResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.UpdatePersonResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AddressBook.Domain.AddressBookServiceReference.GetAllStatesResponse))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private AddressBook.Domain.AddressBookServiceReference.Status StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AddressBook.Domain.AddressBookServiceReference.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Responses")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsSuccessful {
            get {
                return this.IsSuccessfulField;
            }
            set {
                if ((this.IsSuccessfulField.Equals(value) != true)) {
                    this.IsSuccessfulField = value;
                    this.RaisePropertyChanged("IsSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllPeopleResponse", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Responses")]
    [System.SerializableAttribute()]
    public partial class GetAllPeopleResponse : AddressBook.Domain.AddressBookServiceReference.Response {
        
        private System.Collections.Generic.List<AddressBook.Domain.AddressBookServiceReference.PersonRecord> PeopleField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<AddressBook.Domain.AddressBookServiceReference.PersonRecord> People {
            get {
                return this.PeopleField;
            }
            set {
                if ((object.ReferenceEquals(this.PeopleField, value) != true)) {
                    this.PeopleField = value;
                    this.RaisePropertyChanged("People");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddPersonResponse", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Responses")]
    [System.SerializableAttribute()]
    public partial class AddPersonResponse : AddressBook.Domain.AddressBookServiceReference.Response {
        
        private string PersonIdentifierField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PersonIdentifier {
            get {
                return this.PersonIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonIdentifierField, value) != true)) {
                    this.PersonIdentifierField = value;
                    this.RaisePropertyChanged("PersonIdentifier");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeletePeopleResponse", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Responses")]
    [System.SerializableAttribute()]
    public partial class DeletePeopleResponse : AddressBook.Domain.AddressBookServiceReference.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPersonResponse", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Responses")]
    [System.SerializableAttribute()]
    public partial class GetPersonResponse : AddressBook.Domain.AddressBookServiceReference.Response {
        
        private AddressBook.Domain.AddressBookServiceReference.PersonRecord PersonField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AddressBook.Domain.AddressBookServiceReference.PersonRecord Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdatePersonResponse", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Responses")]
    [System.SerializableAttribute()]
    public partial class UpdatePersonResponse : AddressBook.Domain.AddressBookServiceReference.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllStatesResponse", Namespace="http://schemas.datacontract.org/2004/07/AddressBook.Data.Common.Responses")]
    [System.SerializableAttribute()]
    public partial class GetAllStatesResponse : AddressBook.Domain.AddressBookServiceReference.Response {
        
        private System.Collections.Generic.List<AddressBook.Domain.AddressBookServiceReference.StateRecord> StatesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<AddressBook.Domain.AddressBookServiceReference.StateRecord> States {
            get {
                return this.StatesField;
            }
            set {
                if ((object.ReferenceEquals(this.StatesField, value) != true)) {
                    this.StatesField = value;
                    this.RaisePropertyChanged("States");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddressBookServiceReference.IAddressBookService")]
    public interface IAddressBookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBookService/GetAllStates", ReplyAction="http://tempuri.org/IAddressBookService/GetAllStatesResponse")]
        AddressBook.Domain.AddressBookServiceReference.GetAllStatesResponse GetAllStates(AddressBook.Domain.AddressBookServiceReference.GetAllStatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBookService/GetAllStates", ReplyAction="http://tempuri.org/IAddressBookService/GetAllStatesResponse")]
        System.Threading.Tasks.Task<AddressBook.Domain.AddressBookServiceReference.GetAllStatesResponse> GetAllStatesAsync(AddressBook.Domain.AddressBookServiceReference.GetAllStatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBookService/GetAllPeople", ReplyAction="http://tempuri.org/IAddressBookService/GetAllPeopleResponse")]
        AddressBook.Domain.AddressBookServiceReference.GetAllPeopleResponse GetAllPeople(AddressBook.Domain.AddressBookServiceReference.GetAllPeopleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBookService/GetAllPeople", ReplyAction="http://tempuri.org/IAddressBookService/GetAllPeopleResponse")]
        System.Threading.Tasks.Task<AddressBook.Domain.AddressBookServiceReference.GetAllPeopleResponse> GetAllPeopleAsync(AddressBook.Domain.AddressBookServiceReference.GetAllPeopleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBookService/AddPerson", ReplyAction="http://tempuri.org/IAddressBookService/AddPersonResponse")]
        AddressBook.Domain.AddressBookServiceReference.AddPersonResponse AddPerson(AddressBook.Domain.AddressBookServiceReference.AddPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBookService/AddPerson", ReplyAction="http://tempuri.org/IAddressBookService/AddPersonResponse")]
        System.Threading.Tasks.Task<AddressBook.Domain.AddressBookServiceReference.AddPersonResponse> AddPersonAsync(AddressBook.Domain.AddressBookServiceReference.AddPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBookService/DeletePeople", ReplyAction="http://tempuri.org/IAddressBookService/DeletePeopleResponse")]
        AddressBook.Domain.AddressBookServiceReference.DeletePeopleResponse DeletePeople(AddressBook.Domain.AddressBookServiceReference.DeletePeopleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBookService/DeletePeople", ReplyAction="http://tempuri.org/IAddressBookService/DeletePeopleResponse")]
        System.Threading.Tasks.Task<AddressBook.Domain.AddressBookServiceReference.DeletePeopleResponse> DeletePeopleAsync(AddressBook.Domain.AddressBookServiceReference.DeletePeopleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBookService/GetPerson", ReplyAction="http://tempuri.org/IAddressBookService/GetPersonResponse")]
        AddressBook.Domain.AddressBookServiceReference.GetPersonResponse GetPerson(AddressBook.Domain.AddressBookServiceReference.GetPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBookService/GetPerson", ReplyAction="http://tempuri.org/IAddressBookService/GetPersonResponse")]
        System.Threading.Tasks.Task<AddressBook.Domain.AddressBookServiceReference.GetPersonResponse> GetPersonAsync(AddressBook.Domain.AddressBookServiceReference.GetPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBookService/UpdatePerson", ReplyAction="http://tempuri.org/IAddressBookService/UpdatePersonResponse")]
        AddressBook.Domain.AddressBookServiceReference.UpdatePersonResponse UpdatePerson(AddressBook.Domain.AddressBookServiceReference.UpdatePersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBookService/UpdatePerson", ReplyAction="http://tempuri.org/IAddressBookService/UpdatePersonResponse")]
        System.Threading.Tasks.Task<AddressBook.Domain.AddressBookServiceReference.UpdatePersonResponse> UpdatePersonAsync(AddressBook.Domain.AddressBookServiceReference.UpdatePersonRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddressBookServiceChannel : AddressBook.Domain.AddressBookServiceReference.IAddressBookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressBookServiceClient : System.ServiceModel.ClientBase<AddressBook.Domain.AddressBookServiceReference.IAddressBookService>, AddressBook.Domain.AddressBookServiceReference.IAddressBookService {
        
        public AddressBookServiceClient() {
        }
        
        public AddressBookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressBookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressBookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressBookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AddressBook.Domain.AddressBookServiceReference.GetAllStatesResponse GetAllStates(AddressBook.Domain.AddressBookServiceReference.GetAllStatesRequest request) {
            return base.Channel.GetAllStates(request);
        }
        
        public System.Threading.Tasks.Task<AddressBook.Domain.AddressBookServiceReference.GetAllStatesResponse> GetAllStatesAsync(AddressBook.Domain.AddressBookServiceReference.GetAllStatesRequest request) {
            return base.Channel.GetAllStatesAsync(request);
        }
        
        public AddressBook.Domain.AddressBookServiceReference.GetAllPeopleResponse GetAllPeople(AddressBook.Domain.AddressBookServiceReference.GetAllPeopleRequest request) {
            return base.Channel.GetAllPeople(request);
        }
        
        public System.Threading.Tasks.Task<AddressBook.Domain.AddressBookServiceReference.GetAllPeopleResponse> GetAllPeopleAsync(AddressBook.Domain.AddressBookServiceReference.GetAllPeopleRequest request) {
            return base.Channel.GetAllPeopleAsync(request);
        }
        
        public AddressBook.Domain.AddressBookServiceReference.AddPersonResponse AddPerson(AddressBook.Domain.AddressBookServiceReference.AddPersonRequest request) {
            return base.Channel.AddPerson(request);
        }
        
        public System.Threading.Tasks.Task<AddressBook.Domain.AddressBookServiceReference.AddPersonResponse> AddPersonAsync(AddressBook.Domain.AddressBookServiceReference.AddPersonRequest request) {
            return base.Channel.AddPersonAsync(request);
        }
        
        public AddressBook.Domain.AddressBookServiceReference.DeletePeopleResponse DeletePeople(AddressBook.Domain.AddressBookServiceReference.DeletePeopleRequest request) {
            return base.Channel.DeletePeople(request);
        }
        
        public System.Threading.Tasks.Task<AddressBook.Domain.AddressBookServiceReference.DeletePeopleResponse> DeletePeopleAsync(AddressBook.Domain.AddressBookServiceReference.DeletePeopleRequest request) {
            return base.Channel.DeletePeopleAsync(request);
        }
        
        public AddressBook.Domain.AddressBookServiceReference.GetPersonResponse GetPerson(AddressBook.Domain.AddressBookServiceReference.GetPersonRequest request) {
            return base.Channel.GetPerson(request);
        }
        
        public System.Threading.Tasks.Task<AddressBook.Domain.AddressBookServiceReference.GetPersonResponse> GetPersonAsync(AddressBook.Domain.AddressBookServiceReference.GetPersonRequest request) {
            return base.Channel.GetPersonAsync(request);
        }
        
        public AddressBook.Domain.AddressBookServiceReference.UpdatePersonResponse UpdatePerson(AddressBook.Domain.AddressBookServiceReference.UpdatePersonRequest request) {
            return base.Channel.UpdatePerson(request);
        }
        
        public System.Threading.Tasks.Task<AddressBook.Domain.AddressBookServiceReference.UpdatePersonResponse> UpdatePersonAsync(AddressBook.Domain.AddressBookServiceReference.UpdatePersonRequest request) {
            return base.Channel.UpdatePersonAsync(request);
        }
    }
}
