//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBook.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonID { get; set; }
        public int NameID { get; set; }
        public int AddressID { get; set; }
        public int PhoneID { get; set; }
        public int EmailID { get; set; }
        public string PersonIdentifier { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Email Email { get; set; }
        public virtual Name Name { get; set; }
        public virtual Phone Phone { get; set; }
    }
}
