//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationApp.Data
{
  using System;
  using System.Collections.Generic;

  public partial class StudentCourse
  {
    public int StudentCourseId { get; set; }
    public int StudentId { get; set; }
    public int CourseId { get; set; }

    public virtual Course Course { get; set; }
    public virtual Student Student { get; set; }

    public override bool Equals(object obj)
    {
      StudentCourse sc = obj as StudentCourse;
      return sc != null ?
        StudentId == sc.StudentId && CourseId == sc.CourseId
        : false;
    }

    public override int GetHashCode()
    {
      return StudentCourseId + StudentId * CourseId;
    }
  }
}
